Inventory/Controllers/CelebrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.ViewModels;
using Domain.Repositories;
using Core.Services;


namespace Inventory.Controllers
{
    public class CelebrationController : Controller
    {

        private UnitOfWork UnitOfWork;
        private CelebrationServices CelebrationServices;


        public CelebrationController() {

            UnitOfWork = new UnitOfWork();
            CelebrationServices = new CelebrationServices(UnitOfWork);

        }

        // GET: Celebration
        public ActionResult Index()
        {
            var data = CelebrationServices.GetAll();
            return View(data);
        }

        // GET: Celebration/Details/5
        public ActionResult Details(int id)
        {
            var data = CelebrationServices.GetByID(id);
            return View(data);
        }

        // GET: Celebration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Celebration/Create
        [HttpPost]
        public ActionResult Create(CelebrationViewModel celebrationViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                CelebrationServices.Create(celebrationViewModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Celebration/Edit/5
        public ActionResult Edit(int id)
        {
            var data = CelebrationServices.GetByID(id);
            return View(data);
        }

        // POST: Celebration/Edit/5
        [HttpPost]
        public ActionResult Edit(CelebrationViewModel celebrationViewModel)
        {
            try
            {
                // TODO: Add update logic here
                CelebrationServices.Update(celebrationViewModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Celebration/Delete/5
        public ActionResult Delete(int id)
        {
            var data = CelebrationServices.GetByID(id);
            return View(data);
        }

        // POST: Celebration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // TODO: Add delete logic here
                CelebrationServices.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Inventory/Views/Celebration/Create.cshtml
@model Domain.ViewModels.CelebrationViewModel

@{
    ViewBag.Title = "Create";
}



<div class="container">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">Celebration Entry</div>


                </div>

                <div class="panel-body">


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="col-md-10 col-md-offset-1" style="margin-top:15px;">

                                <div class="form-group">
                                    @Html.Label("Celebration Name", htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.CelebrationName, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Please Enter Celebration Name" } })
                                        @Html.ValidationMessageFor(model => model.CelebrationName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            
                                <div class="form-group">


                                    @*<div class="col-md-3 col-md-offset-4">

                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="National" id="National" value="yes" onClick="uncheck(1)">
                                            <label class="form-check-label" for="National">
                                                National
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-md-3">

                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="International" id="International" value="yes" onClick="uncheck(2)">
                                            <label class="form-check-label" for="International">
                                                International
                                            </label>
                                        </div>
                                    </div>*@


                                    <div class="form-group">
                                        @Html.LabelFor(model => model.CelebrationType, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">

                                            <div class="col-md-5">
                                   
                                                @Html.RadioButtonFor(model => model.CelebrationType, "National")
                                                @Html.Label("National", htmlAttributes: new { @class = "control-label" })
                                                </div>
                                            <div class="col-md-6">
                                               
                                                @Html.RadioButtonFor(model => model.CelebrationType, "International")
                                                @Html.Label("International", htmlAttributes: new { @class = "control-label" })
                                                </div>
                                            </div>
                                    </div>




                                </div>



                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                        <a href="@Url.Action("Index", "Celebrations")" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                                        </a>
                                    </div>
                                </div>




                            </div>


                        </div>
                    }


                    



                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

@*<script>
        function checkRefresh(value) {
            document.form1.submit();
        }

        function uncheck(check) {
            var prim = document.getElementById("National");
            var secn = document.getElementById("International");
            if (prim.checked == true && secn.checked == true) {
                if (check == 1) {
                    secn.checked = false;
                    checkRefresh();
                }
                else if (check == 2) {
                    prim.checked = false;
                    checkRefresh();
                }
            }

        }
</script>*@
}

Inventory/Views/Celebration/Delete.cshtml
@model Domain.ViewModels.CelebrationViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CelebrationViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CelebrationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CelebrationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CelebrationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CelebrationType)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inventory/Views/Celebration/Details.cshtml
@model Domain.ViewModels.CelebrationViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CelebrationViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CelebrationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CelebrationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CelebrationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CelebrationType)
        </dd>

       

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CelebrationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory/Views/Celebration/Edit.cshtml
@model Domain.ViewModels.CelebrationViewModel

@{
    ViewBag.Title = "Edit";
}



<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">Update Province Information</div>


                </div>

                <div class="panel-body">


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="col-md-10 col-md-offset-1" style="margin-top:15px;">

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group" style="margin-bottom:5px;">
                                    @Html.LabelFor(model => model.CelebrationName, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.CelebrationName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CelebrationName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                           
                                     @Html.LabelFor(model => model.CelebrationType, htmlAttributes: new { @class = "control-label col-md-4" })
                                   
                                  
                                    <div class="col-md-8">

                                        <div class="col-md-5">

                                            @Html.RadioButtonFor(model => model.CelebrationType, "National")
                                            @Html.Label("National", htmlAttributes: new { @class = "control-label" })
                                        </div>
                                        <div class="col-md-7">

                                            @Html.RadioButtonFor(model => model.CelebrationType, "International")
                                            @Html.Label("International", htmlAttributes: new { @class = "control-label" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                        <a href="@Url.Action("Index", "Celebration")" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }



                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory/Views/Celebration/Index.cshtml
@model IEnumerable<Domain.ViewModels.CelebrationViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CelebrationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CelebrationType)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CelebrationName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CelebrationType)
        </td>
     
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CelebrationId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CelebrationId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CelebrationId })
        </td>
    </tr>
}

</table>