Inventory/Controllers/StateController.cs
using Core.Services;
using Domain.Repositories;
using Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class StateController : Controller
    {
        private StateServices StateServices;
        CountryServices CountryServices;
        private UnitOfWork unitOfWork;



        public StateController()
        {

            unitOfWork = new UnitOfWork();
            StateServices = new StateServices(unitOfWork);
            CountryServices = new CountryServices(unitOfWork);

        }


        // GET: State
        public ActionResult Index()
        {
            var data = StateServices.GetAll();
            return View(data);

        }

        // GET: State/Details/5
        public ActionResult Details(int id)
        {
            var post = StateServices.GetByID(id);
            return View(post);

        }

        // GET: State/Create
        public ActionResult Create()
        {
            loadcountry();
            return View();
        }

        // POST: State/Create
        [HttpPost]
        public ActionResult Create(StateViewModel StateViewModel)
        {
            try
            {
                // TODO: Add insert logic here
                StateServices.Create(StateViewModel);
                TempData["message"] = "Inserted Successfully";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(StateViewModel);
            }
        }

        // GET: State/Edit/5
        public ActionResult Edit(int? id)
        {
            loadcountry();
            StateViewModel StateViewModel = StateServices.GetByID(id);
            return View(StateViewModel);

        }

        // POST: State/Edit/5
        [HttpPost]
        public ActionResult Edit(StateViewModel StateViewModel)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    // TODO: Add update logic here

                    StateServices.Update(StateViewModel);
                    TempData["message"] = "Update Successfully";
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }

            }
           
            return View();
        }

        // GET: State/Delete/5
        public ActionResult Delete(int id)
        {
            var post = StateServices.GetByID(id);
            return View(post);

        }

        // POST: State/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // TODO: Add delete logic here
                StateServices.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        public void loadcountry()
        {
            var countrylist = CountryServices.GetAll();
            ViewBag.countrylist = new SelectList(countrylist, "CountryId", "CountryName");

        }
    }
}

Inventory/Views/State/Create.cshtml
@model Domain.ViewModels.StateViewModel

@{
    ViewBag.Title = "Create";

    string vMessage = "";
    if (TempData.ContainsKey("message"))
    {
        vMessage = TempData["message"].ToString();
        <script type="text/javascript">
            window.onload = function () {

                alert('@TempData["message"]');
            };
        </script>
    }
}

<div class="container">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">State Entry</div>


                </div>

                <div class="panel-body">


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="col-md-10 col-md-offset-1" style="margin-top:15px;">

                                <div class="form-group" style="margin-bottom:5px;">
                                    @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.StateName, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                                        @Html.ValidationMessageFor(model => model.StateName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(a => a.CountryID, ViewBag.countrylist as SelectList, "Please Select Country Name", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                        <a href="@Url.Action("Index", "State")" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                                        </a>
                                    </div>
                                </div>

                            </div>


                        </div>
                    }





                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Inventory/Views/State/Delete.cshtml
@model Domain.ViewModels.StateViewModel

@{
    ViewBag.Title = "Delete";

    string vMessage = "";
    if (TempData.ContainsKey("message"))
    {
        vMessage = TempData["message"].ToString();
        <script type="text/javascript">
            window.onload = function () {

                alert('@TempData["message"]');
            };
        </script>
    }

}


<div class="container">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">Delete State Record</div>


                </div>

                <div class="panel-body">

                    <div class="col-md-8 col-md-offset-2" style="margin-top:15px;">
                        <table class="table table-responsive table-hover">
                            <tr>

                                <th>@Html.DisplayNameFor(model => model.StateID)</th>
                                <td>@Html.DisplayFor(model => model.StateID)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.StateName)</th>
                                <td>@Html.DisplayFor(model => model.StateName)</td>

                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.CountryName)</th>
                                <td>@Html.DisplayFor(model => model.CountryName)</td>

                            </tr>


                        </table>
                        <div class="col-md-12">

                            <p>Are you sure you want to delete this? Click on delete button..</p>

                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2" style="margin-top:15px;">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" />
                                <a href="@Url.Action("Index", "State")" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Inventory/Views/State/Details.cshtml
@model Domain.ViewModels.StateViewModel

@{
    ViewBag.Title = "Details";
}

<div class="container">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">Details of State Record</div>


                </div>

                <div class="panel-body">

                    <div class="col-md-8 col-md-offset-2" style="margin-top:15px;">
                        <table class="table table-responsive table-hover">
                            <tr>

                                <th>@Html.Label("State ID", htmlAttributes: new { @class = "control-label" })</th>
                                <td>@Html.DisplayFor(model => model.StateID)</td>
                            </tr>
                            <tr>
                                <th>@Html.Label("State Name", htmlAttributes: new { @class = "control-label" })</th>
                                <td>@Html.DisplayFor(model => model.StateName)</td>

                            </tr>

                            <tr>
                                <th>@Html.Label("Country Name", htmlAttributes: new { @class = "control-label" })</th>
                                <td>@Html.DisplayFor(model => model.CountryName)</td>

                            </tr>


                        </table>

                    </div>
                    <div class="col-md-8 col-md-offset-2">

                        <div class="form-actions no-color">

                           
                            <a href="@Url.Action("Edit", "State", new { id = Model.StateID })" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-edit"></span> Edit
                            </a>
                            <a href="@Url.Action("Index", "State")" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Inventory/Views/State/Edit.cshtml
@model Domain.ViewModels.StateViewModel

@{
    ViewBag.Title = "Edit";

    string vMessage = "";
    if (TempData.ContainsKey("message"))
    {
        vMessage = TempData["message"].ToString();
        <script type="text/javascript">
            window.onload = function () {

                alert('@TempData["message"]');
            };
        </script>
    }
}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">Update State Information</div>


                </div>

                <div class="panel-body">


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="col-md-10 col-md-offset-1" style="margin-top:15px;">

                            <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group" style="margin-bottom:5px;">
                                    @Html.LabelFor(model => model.StateID, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.StateID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        @Html.ValidationMessageFor(model => model.StateID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group" style="margin-bottom:5px;">
                                    @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.StateName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.StateName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(a => a.CountryID, ViewBag.countrylist as SelectList, "Please Select Country Name", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                        <a href="@Url.Action("Index", "State")" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-arrow-left"></span> Go Back
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }



                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory/Views/State/Index.cshtml
@model IEnumerable<Domain.ViewModels.StateViewModel>

@{
    ViewBag.Title = "Index";

    string vMessage = "";
    if (TempData.ContainsKey("message"))
    {
        vMessage = TempData["message"].ToString();
        <script type="text/javascript">
            window.onload = function () {

                alert('@TempData["message"]');
            };
        </script>
    }
}

<div class="container">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12">

            <div class="panel panel-info card-2 mt">


                <div class="panel-heading">
                    <div class="panel-title">State Information</div>
                </div>

                <div class="panel-body">
                    <div class="row bottom">
                        <div class="col-md-4 pull-left">

                            <div style="margin-bottom:10px;"> <a href="@Url.Action("Create")" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span>Add State</a></div>


                        </div>
                        <div class="col-md-5 col-md-offset-3">


                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                                <input id="Search" type="text" class="form-control" name="Search" placeholder="Enter text to search..">
                            </div>



                        </div>


                    </div>
                    <div class="table-responsive">
                        <table class="table table table-responsive table-bordered table-hover">
                            <thead class="bgdefault">
                                <tr>

                                    <th>
                                        @Html.DisplayNameFor(model => model.StateName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CountryName)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>

                                @foreach (var item in Model)
                                {
                                    <tr class="Search">

                                        <td>
                                            @Html.DisplayFor(modelItem => item.StateName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CountryName)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit",new {id = item.StateID})" title="Edit Category" class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-edit"></span></a>
                                            <a href="@Url.Action("Details",new { id = item.StateID})" title="Details Category" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                            <a href="@Url.Action("Delete",new { id = item.StateID})" title="Delete Category" class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span></a>

                                        </td>
                                    </tr>
                                }

</table>
                    </div>

</div>
</div>
</div>
</div>
</div>



<script>

    $(document).ready(function () {

        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }

        $("#Search").keyup(function () {

            var searchText = $("#Search").val().toLowerCase();
            $(".Search").each(function () {

                if (!Contains($(this).text().toLowerCase(), searchText)) {

                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            });

        });

    });

</script>